name: CD

on:
  push:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
