name: create infrastructure

on:
  workflow_dispatch:
    # allows to execute manually
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      state_bucket_name: ${{ secrets.state_bucket_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup working dir
        working-directory: ./infra/environments

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Set up Terragrunt
        run: |
          curl -LJO https://github.com/gruntwork-io/terragrunt/releases/download/v0.30.0/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      # - name: Run terraform steps
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_wrapper: false
      # - run: terraform init
      # - run: terraform plan
      # - name: Apply Terraform changes
      #   id: apply
      #   run: terraform apply --auto-approve -lock=false
      # - name: destroy
      #   run: terragrunt destroy --auto-approve -lock=false   #remove later if works
